### ISSUE TITLE
TradfriActor Wireless PIR Sensor doesn´t update status.

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-tradfri#22]
#### Pimatic version :
pimatic version 0.9.42

#### Plugin version : 
"pimatic-tradfri" (0.1.17)

#### Problem / Feature :
Wireless TradfriActor doesnt Update status.
Always status active.

#### Expected :
Change in Status to "active" when movement detected, else disabled.

**Comment by treban** [comment]
@scobby Sorry, but this is not feasible.

The problem is that the tradfri gateway does not generate an event.
So I can't see this. 
The presence status of the device only indicates that this device is online in the radio network. 
This also applies to the remote controls. 

I'm developing a plugin that uses the [deconz/raspbee/conbee zigbee modules](https://www.dresden-elektronik.de/raspbee/). (35€ amazon)

This means that both the remote control and the motion sensor can be used independently.
And all zigbee lights are also compatible.
[see here](https://github.com/treban/pimatic-raspbee)

It works very well and I want to release the plugin in a few days.

**Comment by treban** [comment]
I will update the readme, to make it clear

**Comment by michbeck100** [comment]
Sorry to comment on the closed ticket, but i would have the same request. I've seen that some of the pimatic-tradfri devices are getting informed by using setObserver. Can't you use this for the motion sensor, too?

**Comment by treban** [comment]
No :(  Observing the motion sensor / remotes has no effect. 
The gateway has the peculiarity not to send messages about sensor events. 
since firmware version  1.2.42 also group events aren't sent properly.
