### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by WasVerzachter** [treban/pimatic-tradfri#33]

**Comment by sverrevh** [comment]
This can't be done as the API doesn't support it. See also:  https://github.com/treban/pimatic-tradfri/issues/22

**Comment by treban** [comment]
HI, @WasVerzachter, 

as  @sverrevh already mentioned, the gateway does not report status information about sensor or buttons over the api.
since firmware version 1.2.42 also group events aren't sent properly. 

A good alternative is to use a generic zigbee dongle like the deconz hardware. 

**raspberry-pi addon** 
https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/raspbee/

**usb dongel**
https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/conbee/

**and my pimatic-raspbee plugin**
https://github.com/treban/pimatic-raspbee
